[package]
name = "waterwheel"
version = "0.1.0"
authors = ["Steve Lee <sphen.lee@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.115"
serde_json = "1.0.57"
clap = "2.33.3"
log = "0.4.11"
env_logger = "0.7.1"
lapin = "1.2.1"
async-std = "1.6.3"
tide = "0.13.0"
async-amqp = "0.1.5"
sqlx = { version = "0.4.0-beta.1", features = ["postgres", "chrono", "uuid"] }
dotenv = "0.15.0"
anyhow = "1.0.32"
chrono = "0.4.15"
futures = "0.3.5"
binary-heap-plus = "0.3.0"
once_cell = "1.4.0"
bollard = "0.7.2"
tokio = { version = "0.2.22", features = [ "rt-core" ] }
serde_yaml = "0.8.13"
uuid = { version = "0.8.1", features = [ "v4", "serde" ] }

