[package]
name = "waterwheel"
version = "0.1.0"
authors = ["Steve Lee <sphen.lee@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.115"
serde_json = "1.0.57"
clap = "2.33.3"
log = "0.4.11"
env_logger = "0.7.1"
lapin = "1.2.1"
highnoon = { path = "../highnoon" }
tokio-amqp = "0.1"
sqlx = { version = "0.4", features = ["postgres", "chrono", "uuid", "runtime-tokio-rustls"] }
dotenv = "0.15.0"
anyhow = "1.0.32"
chrono = "0.4.15"
futures = "0.3.5"
binary-heap-plus = "0.3.0"
once_cell = "1.4.0"
bollard = "0.8.0"
tokio = { version = "0.2.22", features = [ "rt-core", "dns" ] }
serde_yaml = "0.8.13"
uuid = { version = "0.8.1", features = [ "v4", "serde" ] }
humantime = "2.0.1"
typemap = "0.3.3"
kv-log-macro = "1.0.7"
colored = "2.0.0"
log4rs = "0.13.0"
cron = "0.6.1"
thiserror = "1.0.20"
