version: '2.0'
services:
  amqp:
    image: rabbitmq:management-alpine
    ports:
      - "5672:5672"
      - "8055:15672"

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD
    ports:
      - "5432:5432"

  vector:
    image: timberio/vector:latest-alpine
    ports:
      - "9000:9000"
    volumes:
      - "$PWD/vector.toml:/etc/vector/vector.toml:ro"
      - "$PWD/logs/:/var/log/waterwheel/"

