# this file launch just the services needed to run waterwheel locally
# launch this using `just up` to develop and debug without having to build the Docker image

version: '2.0'

services:
  amqp:
    image: rabbitmq:management-alpine
    ports:
      - "5672:5672"
      - "8055:15672"

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD
    ports:
      - "5432:5432"
