apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: seal
  name: sealproxy-config
data:
  sealproxy.yml: |
    server:
      bind: 0.0.0.0:8081
      x-tls:
        cert_file: /etc/sealproxy/tls/tls.crt
        key_file: /etc/sealproxy/tls/tls.key

    filters:
      - anonymous:
          paths:
            - "/static/**"
            - "/heathcheck"
            - "/int-api/**"

      - form_login:
          path: /login
          success_redirect: /
          failure_redirect: /login
          user_base: &userbase
            user_pass:
              users:
                - ["admin", "password"]
                - ["user", "123456"]

      - cookie_session:
          public_key_file: /etc/sealproxy/pubkey/public.pem

      - redirect:
          location: /login
          paths:
            - "/**"
            - "/"
          not_paths:
            - "/api/**"

    session:
      private_key: /etc/sealproxy/pubkey/private.pem

    target:
      url: http://localhost:8080/
