# A docker compose file for creating a full Waterwheel environment
# Convert it into Kubernetes files using kompose

version: '3.4'

x-definitions:
  waterwheel: &waterwheel
    image: waterwheel:local
    environment:
      - WATERWHEEL_DB_URL=postgres://postgres:$POSTGRES_PASSWORD@db/
      - WATERWHEEL_AMQP_ADDR=amqp://amqp//
      - WATERWHEEL_HMAC_SECRET=wwsharedsecret
      - WATERWHEEL_SERVER_ADDR=http://ww-api-tcp/
      - WATERWHEEL_SERVER_BIND=0.0.0.0:8080
      - WATERWHEEL_TASK_ENGINE=kubernetes
      # TODO - disable authz because there is no authn yet
      #- WATERWHEEL_OPA_SIDECAR_ADDR=http://opa:8181/
      - WATERWHEEL_NO_AUTHZ=true

volumes:
  dbdata:

configs:
  opa-policy:
    file: "./policy/policy.rego"

services:
  amqp:
    image: rabbitmq:management-alpine
    ports:
      - "5672:5672"
      - "8055:15672"
    logging:
      driver: none

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: dbdata
        target: /var/lib/postgresql/data
    logging:
      driver: none

  opa:
    image: openpolicyagent/opa
    ports:
      - "8181:8181"
    configs:
      - source: opa-policy
        target: /policy/policy.rego
    command: [ "run", "--server", "-b", "/policy" ]

  ww-scheduler:
    <<: *waterwheel
    command: ["scheduler"]

  ww-worker:
    <<: *waterwheel
    command: [ "worker" ]
    deploy:
      mode: replicated
      replicas: 4

  ww-api:
    <<: *waterwheel
    command: ["api"]
    ports:
      - "80:8080"
    deploy:
      mode: replicated
      replicas: 2
    labels:
      kompose.service.type: LoadBalancer
